Working version of the multi-path-multi-projects
dldl/sphinx-preview pull request #15
Opened 2018-11-26 15:33 UTC by andreycizov

There's one thing to discuss: how do we manage the destruction of the created containers?

I am leaving this up to the maintainer, but currently all containers created are assigned the same label, so that it would be easy to remove them via command line.

2018-11-26 23:54 UTC, hileef commented
I like this very much, awesome work ! 😃

I have a few suggestions : 

- labelPrefix should be `fr.dldl.sphinx-server` instead of `com.dldl.sphinx-server` as `dldl.fr` is registered and owned by @quentinus95 , and `dldl.com` is not.

- I think it would be better to add logic to the containers port numbers, ( for example with something like [find-port](https://github.com/kessler/find-port) ) as right now it just starts adding up from `54334` and doesn't check if the port is already used, which could cause unfriendly errors.

Finally, I agree that we should get @Coac 's input on a container destruction/cleanup strategy.
Maybe atom provides hooks for the plugin when it closes ?

2018-11-27 20:15 UTC, Coac reviewed
Thanks for the PR.

I agree with @hileef, the label should be `fr.dldl.sphinx-server` and using available random port would be great.

There is a problem with the current version with your changes, the container name has a trailing `=` that is not allowed by docker.
So we are getting this error 
```
(HTTP code 400) unexpected - Invalid container name (sphinx-preview-L2hvbWUvY29hYy9Qcm9qZWN0cy90ZXN0X3NwaGlueA=), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

2018-11-27 20:24 UTC, quentinus95 submitted a review, later dismissed

2018-11-27 20:24 UTC, quentinus95 commented on lib/sphinx-preview.js
> +      .replace('=', '');
Replace only removes the first occurence. If the base64 finishes with two equals it will fail.

2018-11-27 20:24 UTC, quentinus95 commented on lib/sphinx-preview.js
> +    const subName = btoa(serverPath)
It would be better to use a hash function here.

2018-11-27 20:24 UTC, quentinus95 commented on lib/sphinx-preview.js
> +
Remove the empty lines.

2018-12-05 13:14 UTC, andreycizov commented
So now we use `find-free-port` to find a free port, then put it into the container label. It allows for a better interaction between separate windows of Atom: e.g. if you've got the same folder opened in two windows at the same time, they'll reuse the same docker container in order to build it.

2018-12-05 14:24 UTC, hileef requested changes

2018-12-05 14:24 UTC, hileef commented on lib/sphinx-preview.js
> +    let path =  `/${projectPath.replace(/[/\\*]/g, '/').replace(':', '')}`; // WINDOWS
```suggestion
    let path =  `${projectPath.replace(/[/\\*]/g, '/').replace(':', '')}`;
```

The leading slash for supporting windows is already added only when necessary in the lines below.
(In order to not have it when running on macOS)

2018-12-05 16:26 UTC, hileef commented
@andreycizov , thanks for all this work 🙂 !

@Coac , @quentinus95 , do you have access to a windows machine to test this ?

@Coac , I suggest that we create a new issue and PR for the container cleanup strategy, and merge this first, if you are okay with that.

2018-12-05 16:26 UTC, hileef approved these changes

2018-12-05 21:36 UTC, quentinus95 requested changes

2018-12-05 21:36 UTC, quentinus95 commented on lib/sphinx-preview.js
> +    var hash =  new Hashes.SHA256
Correct me if I'm wrong, but don't we have access to NodeJS native libraries here? If so, I would prefer usage of the native library https://nodejs.org/api/crypto.html

2018-12-05 22:33 UTC, quentinus95 approved these changes

2018-12-08 23:03 UTC, Coac approved these changes

2018-12-08 23:03 UTC, merged